version: '3.1'

services:
  redis:
    image: redis:latest
    command: ["redis-server", "--maxclients", "250", "--maxmemory", "1gb"]
    ports:
      - "6379:6379"

  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  ingest:
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    build:
      dockerfile: Dockerfile.ingest

  gql:
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    build:
      dockerfile: Dockerfile.gql
    ports:
      - "3000:3000"
