
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--maxclients", "250", "--maxmemory", "1gb"]
    ports:
      - "6379:6379"

  postgres:
    image: timescale/timescaledb-ha:pg15-latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
