export enum Roles {
  ADD_STRATEGY_MANAGER = 1,
  REVOKE_STRATEGY_MANAGER = 2,
  FORCE_REVOKE_MANAGER = 4,
  ACCOUNTANT_MANAGER = 8,
  QUEUE_MANAGER = 16,
  REPORTING_MANAGER = 32,
  DEBT_MANAGER = 64,
  MAX_DEBT_MANAGER = 128,
  DEPOSIT_LIMIT_MANAGER = 256,
  WITHDRAW_LIMIT_MANAGER = 512,
  MINIMUM_IDLE_MANAGER = 1024,
  PROFIT_UNLOCK_MANAGER = 2048,
  DEBT_PURCHASER = 4096,
  EMERGENCY_MANAGER = 8192
}
