
crons:
  - name: BlockPoller
    queue: block-poll
    schedule: "*/5 * * * * *" # every 5 seconds

  # - name: PricePoller
  #   queue: price-poll
  #   schedule: "*/30 * * * *" # every 30 minutes

  # - name: YearnVaultTvlCatchup
  #   queue: yearn-vault-pointer
  #   job: tvl-catchup
  #   schedule: "*/5 * * * *" # every 5 minutes

processRecycleMs: 600_000 # 10 minutes

processorPools:
  - type: BlockWatcher
    size: 0
  - type: BlockPoller
    size: 1
  - type: BlockLoader
    size: 1
  - type: PricePoller
    size: 1
  - type: PriceLoader
    size: 1
  - type: TvlLoader
    size: 1
  - type: YearnIndexer
    size: 1
  - type: YearnRegistryWatcher
    size: 0
  - type: YearnRegistryBlockPointer
    size: 1
  - type: YearnRegistryExtractor
    size: 1
  - type: YearnVaultPointer
    size: 1
  - type: YearnVaultExtractor
    size: 1
  - type: YearnVaultLoader
    size: 1
  - type: YearnStrategyExtractor
    size: 1
  - type: YearnStrategyLoader
    size: 1
  - type: Loader
    size: 1
    concurrency: 1
