
crons:
  - name: LatestBlocks
    queue: extract
    job: block
    schedule: "*/5 * * * * *" # every 5 seconds

  - name: IngestProbe
    queue: probe
    job: ingest
    schedule: "*/5 * * * * *" # every 5 seconds

  - name: IndexRegistries
    queue: fanout
    job: registry
    schedule: "1-59/5 * * * *" # every 5 minutes

  - name: IndexVaults
    queue: fanout
    job: vault
    schedule: "2-59/5 * * * *" # every 5 minutes

  - name: IndexApeTaxVaults
    queue: extract
    job: apetax
    schedule: "3-59/5 * * * *" # every 5 minutes

  - name: ComputeTvl
    queue: fanout
    job: tvl
    schedule: "3-59/5 * * * *" # every 5 minutes

  - name: ComputeApy
    queue: fanout
    job: apy
    schedule: "4-59/5 * * * *" # every 5 minutes

  - name: ComputeHarvestApr
    queue: fanout
    job: harvest-apr
    schedule: "5-59/5 * * * *" # every 5 minutes

processors:
  - name: Fanout
  - name: Extract
  - name: Compute
  - name: Loader
  - name: Probe

processRecycleMs: 600_000 # 10 minutes
