
crons:
  - name: PollBlock
    queue: poll
    job: block
    schedule: "*/5 * * * * *" # every 5 seconds

  # - name: CatchupVaultBlockPointers
  #   queue: yearn-vault-pointer
  #   job: catchup-block
  #   schedule: "*/5 * * * *" # every 5 minutes

  # - name: CatchupVaultTvlPointers
  #   queue: yearn-vault-pointer
  #   job: catchup-tvl
  #   schedule: "*/5 * * * *" # every 5 minutes

  # ####################################

  # - name: IndexVaultRegistries
  #   queue: fanout
  #   job: registry
  #   schedule: "*/5 * * * *" # every 5 minutes

  # - name: ComputeHarvestApr
  #   queue: fanout
  #   job: harvest-apr
  #   schedule: "*/5 * * * *" # every 5 minutes

  # - name: IndexApeTaxVaults
  #   queue: extract
  #   job: apetax
  #   schedule: "*/5 * * * *" # every 5 minutes

processRecycleMs: 600_000 # 10 minutes

processors:
  - name: Poll
  - name: Fanout
  - name: Extract
  - name: Compute
  - name: Loader
