
cron: 
  name: AbiFanout
  queue: fanout
  job: abis
  schedule: '*/15 * * * *'
  start: false

abis:
  - abiPath: 'yearn/3/registry'
    sources: [
      { chainId: 137, address: '0xfF5e3A7C4cBfA9Dd361385c24C3a0A4eE63CE500', inceptBlock: 49100596 }
    ]

  - abiPath: 'yearn/3/registry2'
    sources: [
      { chainId: 1, address: '0xff31A1B020c868F6eA3f61Eb953344920EeCA3af', inceptBlock: 19072527 },
      { chainId: 100, address: '0xff31A1B020c868F6eA3f61Eb953344920EeCA3af', inceptBlock: 32902749 },
      { chainId: 137, address: '0xff31A1B020c868F6eA3f61Eb953344920EeCA3af', inceptBlock: 52488140 },
      { chainId: 42161, address: '0xff31A1B020c868F6eA3f61Eb953344920EeCA3af', inceptBlock: 171850013 },
    ]

  - abiPath: 'yearn/3/vaultFactory'
    sources: [
      { chainId: 1, address: '0xE9E8C89c8Fc7E8b8F23425688eb68987231178e5', inceptBlock: 18385809 },
      { chainId: 1, address: '0x444045c5C13C246e117eD36437303cac8E250aB0', inceptBlock: 19372662 },
      { chainId: 100, address: '0xE9E8C89c8Fc7E8b8F23425688eb68987231178e5', inceptBlock: 31789111 },
      { chainId: 100, address: '0x444045c5C13C246e117eD36437303cac8E250aB0', inceptBlock: 32784248 },
    ]

  - abiPath: 'yearn/3/vault'
    things: {
      label: 'vault',
      filter: [{ field: 'apiVersion', op: '>=', value: '3.0.0' }]
    }

  - abiPath: 'yearn/3/strategy'
    things: {
      label: 'strategy',
      filter: [{ field: 'apiVersion', op: '>=', value: '3.0.0' }]
    }
    sources: [
      { chainId: 100, address: '0x1b66B4a3a80eBCFA3eCaBf5580cD9929ABa57bb1', inceptBlock: 32996757 },
      { chainId: 100, address: '0xA48359e7E970BE9f38fB6D183C57c8d0b28268B9', inceptBlock: 33306010 },
      { chainId: 100, address: '0x5012C6bf79b3047ECFFf2F212DfFDA4d2128188f', inceptBlock: 32895501 },
      { chainId: 100, address: '0x94c5786393Ab223e0fC111D7463405F165CE86e3', inceptBlock: 33349837 },
      { chainId: 100, address: '0x99474363F03D21375dA1aF4C9694cabCF995e02a', inceptBlock: 32895582 },
      { chainId: 100, address: '0x4B40C9FF9D654Fd7f1E24eD66d8f0f260b199b43', inceptBlock: 32945516 }
    ]

  - abiPath: 'yearn/3/accountant'
    things: {
      label: 'accountant',
      filter: []
    }

  - abiPath: 'yearn/3/debtManagerFactory'
    sources: [
      { chainId: 137, address: '0x0D1F62247035BBFf16742B0f31e8e2Af3aCd6e67', inceptBlock: 51403739 },
    ]

  - abiPath: 'yearn/3/debtAllocator'
    things: {
      label: 'debtAllocator',
      filter: []
    }

  - abiPath: 'yearn/2/registry'
    sources: [
      { chainId: 1, address: '0xe15461b18ee31b7379019dc523231c57d1cbc18c', inceptBlock: 11563389 },
      { chainId: 1, address: '0x50c1a2eA0a861A967D9d0FFE2AE4012c2E053804', inceptBlock: 12045555 },
      { chainId: 10, address: '0x1ba4eB0F44AB82541E56669e18972b0d6037dfE0', inceptBlock: 18097341 },
      { chainId: 250, address: '0x727fe1759430df13655ddb0731dE0D0FDE929b04', inceptBlock: 18455565 },
      { chainId: 42161, address: '0x3199437193625DCcD6F9C9e98BDf93582200Eb1f', inceptBlock: 4841854 }
    ]

  - abiPath: 'yearn/2/registry2'
    sources: [
      { chainId: 1, address: '0xaF1f5e1c19cB68B30aAD73846eFfDf78a5863319', inceptBlock: 16215519 },
      { chainId: 10, address: '0x79286Dd38C9017E5423073bAc11F53357Fc5C128', inceptBlock: 22451152 },
      { chainId: 8453, address: '0xF3885eDe00171997BFadAa98E01E167B53a78Ec5', inceptBlock: 3263730 }
    ]

  - abiPath: 'yearn/2/vault'
    things: {
      label: 'vault',
      filter: [{ field: 'apiVersion', op: '<', value: '3.0.0' }]
    }

  - abiPath: 'yearn/2/strategy'
    things: {
      label: 'strategy',
      filter: [{ field: 'apiVersion', op: '<', value: '3.0.0' }]
    }

  - abiPath: 'yearn/2/tradeHandler'
    things: {
      label: 'tradeHandler',
      filter: []
    }
