
cron: 
  name: AbiFanout
  queue: fanout
  job: abis
  schedule: '*/15 * * * *'
  start: false

abis:
  - abiPath: 'yearn/2/registry'
    sources: [
      { chainId: 1, address: '0x50c1a2eA0a861A967D9d0FFE2AE4012c2E053804', inceptBlock: 12045555 },
    ]

  - abiPath: 'yearn/2/vault'
    sources: [
      { chainId: 1, address: '0xa258C4606Ca8206D8aA700cE2143D7db854D168c', inceptBlock: 12588794 },
    ]

  - abiPath: 'yearn/2/strategy'
    things: {
      label: 'strategy',
      filter: [{ field: 'apiVersion', op: '<', value: '3.0.0' }]
    }
