
contracts:
  - abiPath: 'yearn/3/registry-0'
    schedule: '0-59/30 * * * *'
    fromIncept: true
    sources: [
      {
        chainId: 137,
        address: '0xfF5e3A7C4cBfA9Dd361385c24C3a0A4eE63CE500',
        inceptBlock: 49100596
      }
    ]

  - abiPath: 'yearn/3/registry-1'
    schedule: '0-59/30 * * * *'
    fromIncept: true
    sources: [
      {
        chainId: 137,
        address: '0xff31A1B020c868F6eA3f61Eb953344920EeCA3af',
        inceptBlock: 52488140
      }
    ]

  - abiPath: 'yearn/3/vault'
    schedule: "0-59/30 * * * *"
    things: {
      label: 'vault',
      filter: [{ field: 'apiVersion', op: '>=', value: '3.0.0' }]
    }


    # snapshot: [
    #   {
    #     functionName: 'balanceOf',
    #     args: ['0x2f2a2543B76A4166549F7aab2e75Bef0aefC5B0f'],
    #     thing: { label: 'vault' }
    #   }
    # ]
