
contracts:
  - abiPath: 'yearn/3/registry'
    schedule: '0-59/30 * * * *'
    fromIncept: true
    sources: [
      { chainId: 137, address: '0xfF5e3A7C4cBfA9Dd361385c24C3a0A4eE63CE500', inceptBlock: 49100596 }
    ]

  - abiPath: 'yearn/3/registry2'
    schedule: '0-59/30 * * * *'
    fromIncept: true
    sources: [
      { chainId: 1, address: '0xff31A1B020c868F6eA3f61Eb953344920EeCA3af', inceptBlock: 19072527 },
      { chainId: 137, address: '0xff31A1B020c868F6eA3f61Eb953344920EeCA3af', inceptBlock: 52488140 }
    ]

  - abiPath: 'yearn/3/vault'
    schedule: "0-59/30 * * * *"
    fromIncept: true
    sources: [
      { chainId: 137, address: '0xA013Fbd4b711f9ded6fB09C1c0d358E2FbC2EAA0', inceptBlock: 49181585 },
    ]
    # things: {
    #   label: 'vault',
    #   filter: [{ field: 'apiVersion', op: '>=', value: '3.0.0' }]
    # }

  - abiPath: 'yearn/3/accountant'
    schedule: "0-59/30 * * * *"
    things: {
      label: 'accountant',
      filter: []
    }

  - abiPath: 'yearn/3/debtManagerFactory'
    schedule: "0-59/30 * * * *"
    fromIncept: true
    sources: [
      { chainId: 137, address: '0x0D1F62247035BBFf16742B0f31e8e2Af3aCd6e67', inceptBlock: 51403739 },
    ]

  - abiPath: 'yearn/3/debtAllocator'
    schedule: "0-59/30 * * * *"
    things: {
      label: 'debtAllocator',
      filter: []
    }

  - abiPath: 'yearn/2/registry'
    schedule: '0-59/30 * * * *'
    fromIncept: true
    sources: [
      { chainId: 1, address: '0xe15461b18ee31b7379019dc523231c57d1cbc18c', inceptBlock: 11563389 },
      { chainId: 1, address: '0x50c1a2eA0a861A967D9d0FFE2AE4012c2E053804', inceptBlock: 12045555 },
      { chainId: 10, address: '0x1ba4eB0F44AB82541E56669e18972b0d6037dfE0', inceptBlock: 18097341 },
      { chainId: 250, address: '0x727fe1759430df13655ddb0731dE0D0FDE929b04', inceptBlock: 18455565 },
      { chainId: 42161, address: '0x3199437193625DCcD6F9C9e98BDf93582200Eb1f', inceptBlock: 4841854 }
    ]

  - abiPath: 'yearn/2/registry2'
    schedule: '0-59/30 * * * *'
    fromIncept: true
    sources: [
      { only: true, chainId: 1, address: '0xaF1f5e1c19cB68B30aAD73846eFfDf78a5863319', inceptBlock: 16215519 },
      { chainId: 10, address: '0x79286Dd38C9017E5423073bAc11F53357Fc5C128', inceptBlock: 22451152 },
      { chainId: 8453, address: '0xF3885eDe00171997BFadAa98E01E167B53a78Ec5', inceptBlock: 3263730 }
    ]

  - abiPath: 'yearn/2/vault'
    schedule: '0-59/30 * * * *'
    only: true
    fromIncept: true
    # things: {
    #   label: 'vault',
    #   filter: [{ field: 'apiVersion', op: '<', value: '3.0.0' }]
    # }
    sources: [
      { chainId: 1, address: '0xaA379c2aA72529d5ec0da8A41e2F41ED7Fe4b48C', inceptBlock: 17432298 }
    ]

  - abiPath: 'yearn/2/strategy'
    schedule: '0-59/30 * * * *'
    things: {
      label: 'strategy',
      filter: [{ field: 'apiVersion', op: '<', value: '3.0.0' }]
    }
