
crons:
  - name: LatestBlocks
    queue: extract
    job: block
    schedule: "*/30 * * * * *" # every 30 seconds
    start: true

  - name: SystemProbe
    queue: probe
    job: all
    schedule: "*/2 * * * * *" # every 2 seconds
    start: true
